Step 1: Load and Audit the Raw Data

In [1]:
import pandas as pd

file_path = "kalimati_tarkari_dataset_merged_cleaned.csv"

df = pd.read_csv(file_path)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isna().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nUnits:")
print(df["unit"].value_counts(dropna=False))

print("\nDate range:")
print(df["date"].min(), "to", df["date"].max())

print("\nFirst five rows:")
display(df.head())

Shape: (356323, 10)

Columns:
['name_original', 'name', 'type', 'color', 'location', 'date', 'unit', 'maximum', 'minimum', 'average']

Data types:
name_original        str
name                 str
type                 str
color                str
location             str
date                 str
unit                 str
maximum          float64
minimum          float64
average          float64
dtype: object

Missing values:
name_original         0
name                  0
type             264419
color            295701
location         271794
date                  0
unit                  0
maximum               0
minimum               0
average               0
dtype: int64

Duplicate rows: 12701

Units:
unit
kg     347005
pc       4962
doz      4356
Name: count, dtype: int64

Date range:
1/1/2014 to 9/9/2024

First five rows:

,name_original,name,type,color,location,date,unit,maximum,minimum,average
0,tomato big nepali,tomato,big,NaN,nepali,6/16/2013,kg,40.0,35.0,37.5
1,tomato small local,tomato,small,NaN,local,6/16/2013,kg,32.0,26.0,29.0
2,potato red,potato,NaN,red,NaN,6/16/2013,kg,21.0,20.0,20.5
3,potato white,potato,NaN,white,NaN,6/16/2013,kg,16.0,15.0,15.5
4,onion dry indian,onion,dry,NaN,indian,6/16/2013,kg,30.0,28.0,29.0

In [2]:
duplicate_rows = df[df.duplicated(keep=False)].sort_values(
    by=["name", "date"]
)

display(duplicate_rows.head(20))

,name_original,name,type,color,location,date,unit,maximum,minimum,average
184999,apple jholey,apple,jholey,NaN,NaN,1/10/2021,kg,200.0,200.0,200.0
185000,apple fuji,apple,fuji,NaN,NaN,1/10/2021,kg,300.0,280.0,290.0
197700,apple jholey,apple,jholey,NaN,NaN,1/10/2021,kg,200.0,200.0,200.0
197701,apple fuji,apple,fuji,NaN,NaN,1/10/2021,kg,300.0,280.0,290.0
185097,apple jholey,apple,jholey,NaN,NaN,1/11/2021,kg,200.0,190.0,195.0
185098,apple fuji,apple,fuji,NaN,NaN,1/11/2021,kg,300.0,280.0,290.0
197798,apple jholey,apple,jholey,NaN,NaN,1/11/2021,kg,200.0,190.0,195.0
197799,apple fuji,apple,fuji,NaN,NaN,1/11/2021,kg,300.0,280.0,290.0
185194,apple jholey,apple,jholey,NaN,NaN,1/12/2021,kg,200.0,190.0,195.0
185195,apple fuji,apple,fuji,NaN,NaN,1/12/2021,kg,300.0,280.0,290.0
197895,apple jholey,apple,jholey,NaN,NaN,1/12/2021,kg,200.0,190.0,195.0
197896,apple fuji,apple,fuji,NaN,NaN,1/12/2021,kg,300.0,280.0,290.0
185291,apple jholey,apple,jholey,NaN,NaN,1/13/2021,kg,200.0,180.0,190.0
185292,apple fuji,apple,fuji,NaN,NaN,1/13/2021,kg,300.0,280.0,290.0
197992,apple jholey,apple,jholey,NaN,NaN,1/13/2021,kg,200.0,180.0,190.0
197993,apple fuji,apple,fuji,NaN,NaN,1/13/2021,kg,300.0,280.0,290.0
185387,apple jholey,apple,jholey,NaN,NaN,1/14/2021,kg,200.0,180.0,190.0
185388,apple fuji,apple,fuji,NaN,NaN,1/14/2021,kg,300.0,280.0,290.0
198088,apple jholey,apple,jholey,NaN,NaN,1/14/2021,kg,200.0,180.0,190.0
198089,apple fuji,apple,fuji,NaN,NaN,1/14/2021,kg,300.0,280.0,290.0

Selecting Targeted Variables

In [3]:
target_vegetables = [
    "tomato",
    "onion",
    "potato",
    "cabbage",
    "cauli",
    "brinjal",
    "chilli",
    "garlic"
]

# Check that all selected vegetables exist in the dataset
available_vegetables = set(df["name"].dropna().unique())

print("Not found:")
print(set(target_vegetables) - available_vegetables)

# Create a separate analysis dataset
analysis_df = df[
    df["name"].isin(target_vegetables) &
    (df["unit"] == "kg")
].copy()

print("Analysis dataset shape:", analysis_df.shape)
display(analysis_df.head())

Not found:
set()
Analysis dataset shape: (85145, 10)

,name_original,name,type,color,location,date,unit,maximum,minimum,average
0,tomato big nepali,tomato,big,NaN,nepali,6/16/2013,kg,40.0,35.0,37.5
1,tomato small local,tomato,small,NaN,local,6/16/2013,kg,32.0,26.0,29.0
2,potato red,potato,NaN,red,NaN,6/16/2013,kg,21.0,20.0,20.5
3,potato white,potato,NaN,white,NaN,6/16/2013,kg,16.0,15.0,15.5
4,onion dry indian,onion,dry,NaN,indian,6/16/2013,kg,30.0,28.0,29.0

In [4]:
print("Rows per vegetable:")
print(analysis_df["name"].value_counts())

print("\nDate range:")
print(
    analysis_df["date"].min(),
    "to",
    analysis_df["date"].max()
)

print("\nVarieties or types:")
display(
    analysis_df[
        ["name", "type", "color", "location"]
    ].drop_duplicates().sort_values(["name", "type"])
)

Rows per vegetable:
name
chilli     14613
tomato     14137
garlic     12623
potato     10855
cabbage     9162
onion       8811
brinjal     7872
cauli       7072
Name: count, dtype: int64

Date range:
1/1/2014 to 9/9/2024

Varieties or types:

           name    type  color location
10      brinjal    long    NaN      NaN
11      brinjal   round    NaN      NaN
6       cabbage     NaN    NaN    local
39      cabbage     NaN    red      NaN
141399  cabbage     NaN    NaN      NaN
155515  cabbage     NaN    NaN    terai
155684    cauli   jyapu    NaN    local
7         cauli     NaN    NaN    local
10150     cauli     NaN    NaN    terai
141071   chilli  akbare  green      NaN
141069   chilli  bullet  green      NaN
64       chilli     dry    NaN      NaN
141070   chilli  machhe  green      NaN
65       chilli     NaN  green      NaN
69       garlic     dry    NaN  chinese
70       garlic     dry    NaN   nepali
67       garlic     NaN  green      NaN
4         onion     dry    NaN   indian
155511    onion     dry    NaN  chinese
32        onion     NaN  green      NaN
142848   potato    mude    red      NaN
2        potato     NaN    red      NaN
3        potato     NaN  white      NaN
141009   potato     NaN    red   indian
0        tomato     big    NaN   nepali
143002   tomato     big    NaN   indian
1        tomato   small    NaN    local
141007   tomato   small    NaN   tunnel
146429   tomato   small    NaN   indian
155259   tomato   small    NaN    terai

In [5]:
duplicate_rows = analysis_df[
    analysis_df.duplicated(keep=False)
].sort_values(
    by=["name", "date"]
)

display(duplicate_rows.head(20))

,name_original,name,type,color,location,date,unit,maximum,minimum,average
184958,brinjal long,brinjal,long,NaN,NaN,1/10/2021,kg,40.0,35.0,37.5
184959,brinjal round,brinjal,round,NaN,NaN,1/10/2021,kg,40.0,35.0,37.5
197659,brinjal long,brinjal,long,NaN,NaN,1/10/2021,kg,40.0,35.0,37.5
197660,brinjal round,brinjal,round,NaN,NaN,1/10/2021,kg,40.0,35.0,37.5
185055,brinjal long,brinjal,long,NaN,NaN,1/11/2021,kg,35.0,30.0,32.5
185056,brinjal round,brinjal,round,NaN,NaN,1/11/2021,kg,40.0,35.0,37.5
197756,brinjal long,brinjal,long,NaN,NaN,1/11/2021,kg,35.0,30.0,32.5
197757,brinjal round,brinjal,round,NaN,NaN,1/11/2021,kg,40.0,35.0,37.5
185153,brinjal long,brinjal,long,NaN,NaN,1/12/2021,kg,40.0,35.0,37.5
185154,brinjal round,brinjal,round,NaN,NaN,1/12/2021,kg,40.0,35.0,37.5
197854,brinjal long,brinjal,long,NaN,NaN,1/12/2021,kg,40.0,35.0,37.5
197855,brinjal round,brinjal,round,NaN,NaN,1/12/2021,kg,40.0,35.0,37.5
185249,brinjal long,brinjal,long,NaN,NaN,1/13/2021,kg,40.0,30.0,35.0
185250,brinjal round,brinjal,round,NaN,NaN,1/13/2021,kg,40.0,30.0,35.0
197950,brinjal long,brinjal,long,NaN,NaN,1/13/2021,kg,40.0,30.0,35.0
197951,brinjal round,brinjal,round,NaN,NaN,1/13/2021,kg,40.0,30.0,35.0
185347,brinjal long,brinjal,long,NaN,NaN,1/14/2021,kg,40.0,30.0,35.0
185348,brinjal round,brinjal,round,NaN,NaN,1/14/2021,kg,40.0,30.0,35.0
198048,brinjal long,brinjal,long,NaN,NaN,1/14/2021,kg,40.0,30.0,35.0
198049,brinjal round,brinjal,round,NaN,NaN,1/14/2021,kg,40.0,30.0,35.0

In [6]:
# Convert date values into datetime format
analysis_df["date"] = pd.to_datetime(
    analysis_df["date"],
    errors="coerce"
)

# Convert price columns into numeric format
price_columns = ["minimum", "maximum", "average"]

for column in price_columns:
    analysis_df[column] = pd.to_numeric(
        analysis_df[column],
        errors="coerce"
    )

print("Data types after conversion:")
print(analysis_df.dtypes)

Data types after conversion:
name_original               str
name                        str
type                        str
color                       str
location                    str
date             datetime64[us]
unit                        str
maximum                 float64
minimum                 float64
average                 float64
dtype: object

In [8]:
print("Missing values after conversion:")
print(analysis_df.isna().sum())

print("\nInvalid price relationships:")
display(
    analysis_df[
        analysis_df["minimum"] > analysis_df["maximum"]
    ][["name", "date", "minimum", "maximum", "average"]].head()
)

Missing values after conversion:
name_original        0
name                 0
type             37661
color            52370
location         43786
date                 0
unit                 0
maximum              0
minimum              0
average              0
dtype: int64

Invalid price relationships:

Empty DataFrame
Columns: [name, date, minimum, maximum, average]
Index: []

In [9]:
zero_price_rows = analysis_df[
    (analysis_df["minimum"] <= 0) |
    (analysis_df["maximum"] <= 0) |
    (analysis_df["average"] <= 0)
]

print("Rows with zero or negative prices:", len(zero_price_rows))

display(
    zero_price_rows[
        ["name", "date", "type", "minimum", "maximum", "average"]
    ].head(20)
)

Rows with zero or negative prices: 0

Empty DataFrame
Columns: [name, date, type, minimum, maximum, average]
Index: []

In [10]:
invalid_average_rows = analysis_df[
    (analysis_df["average"] < analysis_df["minimum"]) |
    (analysis_df["average"] > analysis_df["maximum"])
]

print(
    "Rows where average is outside the minimum-maximum range:",
    len(invalid_average_rows)
)

display(
    invalid_average_rows[
        ["name", "date", "minimum", "maximum", "average"]
    ].head(20)
)

Rows where average is outside the minimum-maximum range: 0

Empty DataFrame
Columns: [name, date, minimum, maximum, average]
Index: []

In [11]:
# Create time-related features
analysis_df["year"] = analysis_df["date"].dt.year
analysis_df["month"] = analysis_df["date"].dt.month
analysis_df["month_name"] = analysis_df["date"].dt.month_name()

# Create price-related features
analysis_df["price_range"] = (
    analysis_df["maximum"] - analysis_df["minimum"]
)

analysis_df["price_spread_percent"] = (
    analysis_df["price_range"] /
    analysis_df["average"]
) * 100

display(
    analysis_df[
        [
            "name",
            "date",
            "year",
            "month",
            "month_name",
            "minimum",
            "maximum",
            "average",
            "price_range",
            "price_spread_percent"
        ]
    ].head()
)

,name,date,year,month,month_name,minimum,maximum,average,price_range,price_spread_percent
0,tomato,2013-06-16,2013,6,June,35.0,40.0,37.5,5.0,13.333333
1,tomato,2013-06-16,2013,6,June,26.0,32.0,29.0,6.0,20.689655
2,potato,2013-06-16,2013,6,June,20.0,21.0,20.5,1.0,4.878049
3,potato,2013-06-16,2013,6,June,15.0,16.0,15.5,1.0,6.451613
4,onion,2013-06-16,2013,6,June,28.0,30.0,29.0,2.0,6.896552

In [12]:
daily_summary = (
    analysis_df
    .groupby(["name", "date"], as_index=False)
    .agg(
        average_price=("average", "median"),
        minimum_price=("minimum", "median"),
        maximum_price=("maximum", "median"),
        price_range=("price_range", "median"),
        price_spread_percent=("price_spread_percent", "median"),
        observations=("average", "size")
    )
)

daily_summary["year"] = daily_summary["date"].dt.year
daily_summary["month"] = daily_summary["date"].dt.month
daily_summary["month_name"] = daily_summary["date"].dt.month_name()

print("Daily summary shape:", daily_summary.shape)

display(daily_summary.head())

Daily summary shape: (33868, 11)

,name,date,average_price,minimum_price,maximum_price,price_range,price_spread_percent,observations,year,month,month_name
0,brinjal,2013-06-16,19.00,18.0,20.0,2.0,10.644258,2,2013,6,June
1,brinjal,2013-06-17,23.25,21.5,25.0,3.5,14.354067,2,2013,6,June
2,brinjal,2013-06-18,25.00,22.5,27.5,5.0,20.202020,2,2013,6,June
3,brinjal,2013-06-19,25.75,23.5,28.0,4.5,17.424242,2,2013,6,June
4,brinjal,2013-06-20,25.00,22.5,27.5,5.0,20.202020,2,2013,6,June

In [13]:
monthly_summary = (
    daily_summary
    .groupby(["name", "month", "month_name"], as_index=False)
    .agg(
        typical_price=("average_price", "median"),
        mean_price=("average_price", "mean"),
        price_volatility=("average_price", "std"),
        days_observed=("average_price", "count")
    )
    .sort_values(["name", "month"])
)

display(monthly_summary.head(20))

,name,month,month_name,typical_price,mean_price,price_volatility,days_observed
0,brinjal,1,January,40.0000,43.067967,12.003377,359
1,brinjal,2,February,45.0000,45.751292,12.788284,325
2,brinjal,3,March,42.5000,47.462471,15.272288,342
3,brinjal,4,April,32.7500,34.883907,9.922852,343
4,brinjal,5,May,37.5000,38.134986,10.847896,358
5,brinjal,6,June,30.0000,32.817836,8.928023,365
6,brinjal,7,July,42.5000,45.612047,18.087407,364
7,brinjal,8,August,37.5000,39.505582,13.945735,361
8,brinjal,9,September,40.0000,41.172457,13.999340,346
9,brinjal,10,October,46.0850,50.318713,18.428213,342
10,brinjal,11,November,42.5000,43.071095,12.977849,347
11,brinjal,12,December,37.5000,40.110028,10.729734,357
12,cabbage,1,January,30.0000,36.849471,20.398293,359
13,cabbage,2,February,29.0000,28.043593,12.875443,327
14,cabbage,3,March,25.0000,26.098812,12.013745,345
15,cabbage,4,April,32.6700,32.073601,14.652108,343
16,cabbage,5,May,38.5000,37.243050,16.529481,359
17,cabbage,6,June,41.7500,42.701429,17.903055,364
18,cabbage,7,July,42.9175,49.145220,25.413628,364
19,cabbage,8,August,55.0000,61.917825,34.078396,361